### ISSUE TITLE
Outputs 404 each time

### ISSUE THREAD

**Issue by njpvm** [fastify/fastify-react#25]
Outputs 404 each time. how to cancel.
--------------------------------------------------------------------------------------------
[2018-03-23T10:31:31.952Z] INFO (7400 on USERCHI-NBKB0FN): incoming request
    reqId: 17
    req: {
      "id": 17,
      "method": "GET",
      "url": "/_next/-/main.js",
      "remoteAddress": "127.0.0.1",
      "remotePort": 52960
    }
[2018-03-23T10:31:31.955Z] INFO (7400 on USERCHI-NBKB0FN): Not found
    reqId: 17
    res: {
      "statusCode": 404
    }
    err: {
      "type": "Error",
      "message": "Not found",
      "stack":
          Error: Not found
              at Context.basic404 [as handler] (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\fastify.js:679:26)
              at preHandlerCallback (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\lib\\handleRequest.js:88:30)
              at handler (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\lib\\handleRequest.js:72:5)
              at handleRequest (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\lib\\handleRequest.js:22:5)
              at onRunMiddlewares (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\fastify.js:346:5)
              at middlewareCallback (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\fastify.js:334:7)
              at Object.routeHandler [as handler] (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\fastify.js:224:7)
              at Router.lookup (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_find-my-way@1.11.1@find-my-way\\index.js:269:17)
              at Router.defaultRoute (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_fastify@1.1.1@fastify\\fastify.js:675:16)
              at Router._defaultRoute (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_find-my-way@1.11.1@find-my-way\\index.js:415:10)
              at Router.lookup (G:\\codes\\mycode\\shuoyan\\vmxue\
          ode_modules\\_find-my-way@1.11.1@find-my-way\\index.js:268:36)
              at emitTwo (events.js:126:13)
              at Server.emit (events.js:214:7)
              at parserOnIncoming (_http_server.js:602:12)
              at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    }
[2018-03-23T10:31:31.958Z] INFO (7400 on USERCHI-NBKB0FN): request completed
    reqId: 17
    res: {
      "statusCode": 404
    }
    responseTime: 6.0355259999632835
> Disposing inactive page(s): /home

**Comment by delvedor** [comment]
Can you paste some basic code to reproduce the issue?

**Comment by njpvm** [comment]
@delvedor 
`
require('make-promises-safe')

const path = require('path')

const dev = process.env.NODE_ENV !== 'prod'

let logConfig
if (dev) {
  logConfig = {
    level: 'info',
    prettyPrint: true
  }
} else {
  logConfig = {
    level: 'info'
  }
}

const fastify = require('fastify')({
  logger: logConfig
})


fastify.register(require('fastify-static'), {
  root: path.join(__dirname, '.next'),
  prefix: '/_next/' // optional: default '/'
})

fastify
  .register(require('./plugins/fastify-react'), {
    dev: false
  })
  .after(() => {
    fastify.next('/')
  })

const AutoLoad = require('fastify-autoload')

fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'src/controller')
})

const start = async () => {
  try {
    if (dev) {
      await fastify.listen(3000, '127.0.0.1')
    } else {
      await fastify.listen(80, '0.0.0.0')
    }
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

`

**Comment by delvedor** [comment]
What is the content of `./plugins/fastify-react'`?

**Comment by njpvm** [comment]
```js
'use strict'

const assert = require('assert')
const fp = require('fastify-plugin')
const Next = require('next')

function fastifyReact(fastify, options, next) {
  const app = Next(
    Object.assign({ dev: process.env.NODE_ENV !== 'production' }, options)
  )

  app
    .prepare()
    .then(() => {
      fastify.decorate('next', route.bind(fastify))
      next()
    })
    .catch(err => next(err))

  function route(path, opts, callback) {
    opts = opts || {}
    if (typeof opts === 'function') {
      callback = opts
      opts = {}
    }

    assert(typeof path === 'string', 'path must be a string')
    if (opts.method)
      assert(typeof opts.method === 'string', 'options.method must be a string')
    if (opts.schema)
      assert(
        typeof opts.schema === 'object',
        'options.schema must be an object'
      )
    if (opts.next)
      assert(typeof opts.next === 'object', 'options.next must be an object')
    if (callback)
      assert(typeof callback === 'function', 'callback must be a function')

    const method = opts.method || 'get'
    this[method.toLowerCase()](path, opts, handler)

    function handler(req, reply) {
      if (callback) {
        return callback(app, req, reply)
      }

      app.render(req.req, reply.res, path, req.query, opts.next || {})
    }
  }
}

module.exports = fp(fastifyReact, {
  fastify: '>=1.0.0',
  name: 'fastify-react'
})

```

**Comment by njpvm** [comment]
@delvedor 
```js
'use strict'

const assert = require('assert')
const fp = require('fastify-plugin')
const Next = require('next')

function fastifyReact(fastify, options, next) {
  const app = Next(
    Object.assign({ dev: process.env.NODE_ENV !== 'production' }, options)
  )

  app
    .prepare()
    .then(() => {
      fastify.decorate('next', route.bind(fastify))
      next()
    })
    .catch(err => next(err))

  function route(path, opts, callback) {
    opts = opts || {}
    if (typeof opts === 'function') {
      callback = opts
      opts = {}
    }

    assert(typeof path === 'string', 'path must be a string')
    if (opts.method)
      assert(typeof opts.method === 'string', 'options.method must be a string')
    if (opts.schema)
      assert(
        typeof opts.schema === 'object',
        'options.schema must be an object'
      )
    if (opts.next)
      assert(typeof opts.next === 'object', 'options.next must be an object')
    if (callback)
      assert(typeof callback === 'function', 'callback must be a function')

    const method = opts.method || 'get'
    this[method.toLowerCase()](path, opts, handler)

    function handler(req, reply) {
      if (callback) {
        return callback(app, req, reply)
      }

      app.render(req.req, reply.res, path, req.query, opts.next || {})
    }
  }
}

module.exports = fp(fastifyReact, {
  fastify: '>=1.0.0',
  name: 'fastify-react'
})

```

**Comment by delvedor** [comment]
Again, I need a complete example to be able to reproduce the issue, what's the content of the next folder?
By the way, why aren't you using directly this plugin?

**Comment by njpvm** [comment]
@delvedor this is a example. https://github.com/njpvm/fastify-react

**Comment by shanurrahman** [comment]
I am getting the same error here not sure why
