### ISSUE TITLE
None of my functions are working

### ISSUE THREAD

**Issue by Snazzyham** [fastify/fastify-react#27]
Out of the box, does Fastify support using ES6? 

I've got a fastify app serving up a Next.js document, but none of my onClick functions are working, and neither are my lifecycle methods.

**Comment by delvedor** [comment]
Can you paste some code?

**Comment by delvedor** [comment]
Does this works if you use `next` alone?

**Comment by Snazzyham** [comment]
you mean if I spin up a next instance separate to fastify? yeah it does.

**Comment by delvedor** [comment]
At the moment I have no time to investigate, if you do, or know someone who can do it, please go ahead! :)
