### ISSUE TITLE
Ready callback borken

### ISSUE THREAD

**Issue by binarykitchen** [fastify/fastify-react#28]
If you use the second example

```js
fastify.ready(() => {
  fastify.next('/index')
})
```

then this error is thrown

```
new Error('root plugin has already booted')
```

**Comment by delvedor** [comment]
Hi, thank your for pointing out.
The documentation is outdated and that example should be removed.
Would you min send a pr?

**Comment by binarykitchen** [comment]
Well, I can't since I don't know the correct syntax.

**Comment by pyros2097** [comment]
yeah... the ready/after callback is broken in the lastest fastify version. It works in the in version ^0.38.0

**Comment by delvedor** [comment]
Please see https://github.com/fastify/fastify-react/pull/31.
