### ISSUE TITLE
Rename to fastify-next

### ISSUE THREAD

**Issue by binarykitchen** [fastify/fastify-react#29]
Because it's not really about React but next.js. There is no direct dependency to React

**Comment by delvedor** [comment]
`next` is one of the best framework to perform react ssr, that's why we are using it.
`fastify-next` is too generic.

**Comment by tsnieman** [comment]
I think `fastify-nextjs` or `fastify-nextjs-react` would be more accurate
names.

**Comment by TheAifam5** [comment]
I think `fastify-next` will be the best option, since uses `next`, so it's not a real "fastify-react" where should integrate only with `fastify` and react's hydrate.

**Comment by millette** [comment]
+1 on renaming to `fastify-next` or even `fastify-nextjs` if the former is deemed too generic.
