### ISSUE TITLE
fastify-react issue including a css file

### ISSUE THREAD

**Issue by Jason-Argos** [fastify/fastify-react#39]

**Comment by mcollina** [comment]
Can you please paste server.js?

**Comment by Jason-Argos** [comment]
Minimal repro in the attached zip file. 

[repro.zip](https://github.com/fastify/fastify-react/files/2539752/repro.zip)

**Comment by mcollina** [comment]
I'm sorry, I've been traveling for the past two weeks, and I'll still be on the road this week.
